# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""gRPC server and client classes for ekyc.v1."""

from __future__ import annotations

import grpc

from . import ekyc_pb2 as ekyc__pb2


class EkycSupportServiceStub(object):
    """Client stub for the EkycSupportService."""

    def __init__(self, channel: grpc.Channel):
        """Instantiate the stub with the given channel."""
        self.PerformKtpOcr = channel.unary_unary(
            "/ekyc.v1.EkycSupportService/PerformKtpOcr",
            request_serializer=ekyc__pb2.KtpOcrRequest.SerializeToString,
            response_deserializer=ekyc__pb2.KtpOcrResponse.FromString,
        )
        self.ProcessEkyc = channel.unary_unary(
            "/ekyc.v1.EkycSupportService/ProcessEkyc",
            request_serializer=ekyc__pb2.EkycRequest.SerializeToString,
            response_deserializer=ekyc__pb2.ProcessEkycResponse.FromString,
        )


class EkycSupportServiceServicer(object):
    """Server API for the EkycSupportService."""

    def PerformKtpOcr(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ProcessEkyc(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EkycSupportServiceServicer_to_server(servicer, server: grpc.Server):
    rpc_method_handlers = {
        "PerformKtpOcr": grpc.unary_unary_rpc_method_handler(
            servicer.PerformKtpOcr,
            request_deserializer=ekyc__pb2.KtpOcrRequest.FromString,
            response_serializer=ekyc__pb2.KtpOcrResponse.SerializeToString,
        ),
        "ProcessEkyc": grpc.unary_unary_rpc_method_handler(
            servicer.ProcessEkyc,
            request_deserializer=ekyc__pb2.EkycRequest.FromString,
            response_serializer=ekyc__pb2.ProcessEkycResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ekyc.v1.EkycSupportService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
