# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""gRPC server and client classes for ekyc.v1."""

from __future__ import annotations

import grpc

from . import ekyc_pb2 as ekyc__pb2


class EkycSupportServiceStub(object):
    """Client stub for the EkycSupportService."""

    def __init__(self, channel: grpc.Channel):
        """Instantiate the stub with the given channel."""
        self.StartFaceMatchJob = channel.unary_unary(
            "/ekyc.v1.EkycSupportService/StartFaceMatchJob",
            request_serializer=ekyc__pb2.StartFaceMatchRequest.SerializeToString,
            response_deserializer=ekyc__pb2.StartFaceMatchResponse.FromString,
        )
        self.StartLivenessJob = channel.unary_unary(
            "/ekyc.v1.EkycSupportService/StartLivenessJob",
            request_serializer=ekyc__pb2.StartLivenessRequest.SerializeToString,
            response_deserializer=ekyc__pb2.StartLivenessResponse.FromString,
        )


class EkycSupportServiceServicer(object):
    """Server API for the EkycSupportService."""

    def StartFaceMatchJob(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StartLivenessJob(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_EkycSupportServiceServicer_to_server(servicer, server: grpc.Server):
    rpc_method_handlers = {
        "StartFaceMatchJob": grpc.unary_unary_rpc_method_handler(
            servicer.StartFaceMatchJob,
            request_deserializer=ekyc__pb2.StartFaceMatchRequest.FromString,
            response_serializer=ekyc__pb2.StartFaceMatchResponse.SerializeToString,
        ),
        "StartLivenessJob": grpc.unary_unary_rpc_method_handler(
            servicer.StartLivenessJob,
            request_deserializer=ekyc__pb2.StartLivenessRequest.FromString,
            response_serializer=ekyc__pb2.StartLivenessResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ekyc.v1.EkycSupportService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
